### ISSUE TITLE
Review design of `kapow server` init process

### ISSUE THREAD

**Issue by nilp0inter** [BBVA/kapow#95] opened 2019-11-25 10:16 UTC
1. `kapow server` is artificially coupled to `/bin/sh` which maybe not present in all supported systems.
2. A file format for rule exchange may be desirable.
3. We will NOT discuss this until we discuss this.

**Comment by hhurtado** [comment] 2020-08-24 12:19
Duplicate of #83, #62 and #64. Will continue here and close the others.

https://github.com/BBVA/kapow/blob/f4b9a96a0648465a076c4b1af3b461a22dff6ec6/internal/cmd/server.go#L55

The idea is to decouple from bash and to execute directly the path given to the kapow server command and delegate in the OS the task of identifying what is the best option.

This will allow to remove the .pow extension and replace it with a better one that let the OS to choose and/or to include inside the file a shebang to instruct the interpreter.

**Closed** 2020-12-24 13:19 UTC
Labels: discussion
